Major codebase reorganization: moved all code into separate modules.
Exception: customer related code still needs to be moved, but I haven't
decided on a structure yet.

WARNING: Achievo is now in a SEVERELY UNSTABLE STATE. Do NOT upgrade
any CVS mainbranch based production installations until the codebase is
stable again. Most features are currently broken because of moved files,
new node names etc.